- name: PHP-FPM | Debian | Install | Make sure the ansible required dependencies are installed
  become: yes
  become_method: su
  apt:
    pkg: python-pycurl
    state: present

- name: PHP-FPM | Debian | Install | Update apt cache with new repo data
  become: yes
  become_method: su
  apt: 
    update_cache: yes

- name: PHP-FPM | Debian | Install | Make sure php-fpm is installed (package)
  become: yes
  become_method: su
  apt:
    pkg: php5-fpm
    state: latest
  notify:
    - PHP-FPM | Handlers | Service restart
